-d C:\Users\Armin\Desktop\ImageProcessing\TangNano20k_DSim_Cloud\project\impl\gwsynthesis\TangNano20k_DSim_Cloud.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cfg C:\Users\Armin\Desktop\ImageProcessing\TangNano20k_DSim_Cloud\project\impl\pnr\device.cfg
-gao C:\Users\Armin\Desktop\ImageProcessing\TangNano20k_DSim_Cloud\project\impl\gao\gao.v
-gao_crc 0000010101110000
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
